In [1]:
import numpy as np

## 初始化numpy

In [2]:
score = np.array(
    [[80, 89, 86, 67, 79],
[78, 97, 89, 67, 81],
[90, 94, 78, 67, 74],
[91, 91, 90, 67, 69],
[76, 87, 75, 67, 86],
[70, 79, 84, 67, 84],
[94, 92, 93, 67, 64],
[86, 85, 83, 67, 80]]
)

In [3]:
score

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

## ndarray和原生Python效率对比

In [4]:
# import random
# import time
# import numpy as np
# a = []
# for i in range(100000000):
#     a.append(random.random())

# # 通过%time魔法方法, 查看当前行的代码运行一次所花费的时间
# %time sum1=sum(a)

# b=np.array(a)

# %time sum2=np.sum(b)

# ndarray的使用

## 数组的属性

In [5]:
score

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

In [6]:
score.shape

(8, 5)

In [7]:
score.ndim

2

In [8]:
score.size

40

In [9]:
score.itemsize

8

In [10]:
score.dtype

dtype('int64')

## 数组的形状

In [11]:
a = np.array([1,2,3])

In [12]:
a

array([1, 2, 3])

In [13]:
a.shape

(3,)

In [14]:
b = np.array([[1,2,3],[1,2,3]])

In [15]:
b

array([[1, 2, 3],
       [1, 2, 3]])

In [16]:
b.shape

(2, 3)

In [17]:
c = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])

In [18]:
c

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [19]:
c.shape

(2, 2, 3)

## 数组的类型

In [20]:
b = np.array([[1,2,3],[1,2,3]],dtype=np.float32)

In [21]:
b

array([[1., 2., 3.],
       [1., 2., 3.]], dtype=float32)

In [24]:
arr = np.array(["pythonI", "hello", "I"], dtype=np.bytes_)

In [25]:
arr

array([b'pythonI', b'hello', b'I'], dtype='|S7')