# ndarray的运算

In [2]:
import numpy as np


## 逻辑运算

In [6]:
score = np.random.randint(40,100,(10,5))

In [7]:
score

array([[88, 57, 74, 57, 54],
       [59, 85, 76, 51, 88],
       [98, 96, 79, 96, 89],
       [88, 46, 92, 56, 76],
       [72, 82, 68, 65, 61],
       [86, 93, 53, 89, 64],
       [60, 78, 41, 75, 53],
       [97, 69, 41, 46, 44],
       [75, 46, 54, 95, 84],
       [72, 94, 41, 80, 52]], dtype=int32)

In [8]:
test_score = score[6:,0:4]

In [9]:
test_score

array([[60, 78, 41, 75],
       [97, 69, 41, 46],
       [75, 46, 54, 95],
       [72, 94, 41, 80]], dtype=int32)

In [10]:
test_score > 60

array([[False,  True, False,  True],
       [ True,  True, False, False],
       [ True, False, False,  True],
       [ True,  True, False,  True]])

In [11]:
test_score[test_score>60] =1

In [12]:
test_score

array([[60,  1, 41,  1],
       [ 1,  1, 41, 46],
       [ 1, 46, 54,  1],
       [ 1,  1, 41,  1]], dtype=int32)

## 通用判断函数

In [27]:
np.all(score[0:2,]>80)

np.False_

In [29]:
np.any(score[0:2,]>80)

np.True_

## np.where（三元运算符）

In [32]:
temp=score[:4,:4]
temp

array([[88, 57, 74, 57],
       [59, 85, 76, 51],
       [98, 96, 79, 96],
       [88, 46, 92, 56]], dtype=int32)

In [33]:
np.where(temp>60,1,0)

array([[1, 0, 1, 0],
       [0, 1, 1, 0],
       [1, 1, 1, 1],
       [1, 0, 1, 0]])

In [38]:
np.where(np.logical_and(temp>60,temp<90),1,0)

array([[1, 0, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0]])

In [39]:
np.where(np.logical_or(temp>90,temp<60),1,0)

array([[0, 1, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 0, 1],
       [0, 1, 1, 1]])

# 统计指标

In [ ]:
## axis=0 按列 axis = 1 按行

In [40]:
score

array([[88, 57, 74, 57, 54],
       [59, 85, 76, 51, 88],
       [98, 96, 79, 96, 89],
       [88, 46, 92, 56, 76],
       [72, 82, 68, 65, 61],
       [86, 93, 53, 89, 64],
       [60,  1, 41,  1, 53],
       [ 1,  1, 41, 46, 44],
       [ 1, 46, 54,  1, 84],
       [ 1,  1, 41,  1, 52]], dtype=int32)

In [42]:
temp = score[:6,]
temp

array([[88, 57, 74, 57, 54],
       [59, 85, 76, 51, 88],
       [98, 96, 79, 96, 89],
       [88, 46, 92, 56, 76],
       [72, 82, 68, 65, 61],
       [86, 93, 53, 89, 64]], dtype=int32)

In [43]:
np.max(temp)

np.int32(98)

In [44]:
np.min(temp)

np.int32(46)

In [45]:
np.mean(temp)

np.float64(74.6)

In [50]:
np.median(temp,axis=1)

array([57., 76., 96., 76., 68., 86.])

In [46]:
np.max(temp,axis=0)

array([98, 96, 92, 96, 89], dtype=int32)

In [47]:
np.max(temp,axis=1)

array([88, 88, 98, 92, 82, 93], dtype=int32)

In [51]:
np.argmax(temp)

np.int64(10)

In [52]:
np.argmax(temp,axis=0)

array([2, 2, 3, 2, 2])

In [53]:
np.argmin(temp)

np.int64(16)

In [54]:
np.argmin(temp,axis=0)

array([1, 3, 5, 1, 0])

In [55]:
np.std(temp)

np.float64(15.58760191092053)

In [56]:
np.var(temp)

np.float64(242.97333333333336)

# 数组间的运算

In [58]:
arr = np.array([[1,2,3],[3,4,5]])

In [59]:
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [63]:
arr+3

array([[4, 5, 6],
       [6, 7, 8]])

In [64]:
arr/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.        , 1.33333333, 1.66666667]])

In [66]:
arr*3

array([[ 3,  6,  9],
       [ 9, 12, 15]])

In [67]:
a = [1,2,3]

In [68]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [69]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])

In [70]:
# arr1 + arr2 # 不可以进行计算

In [112]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1],[2]])


In [113]:
arr1.shape

(2, 6)

In [114]:
arr2.shape

(2, 1)

In [115]:
arr2+arr1

array([[2, 3, 4, 3, 2, 5],
       [7, 8, 3, 4, 5, 3]])

# 矩阵运算

In [ ]:
## np.matmul np.dot

In [118]:
a = np.array([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])

In [119]:
a

array([[80, 86],
       [82, 80],
       [85, 78],
       [90, 90],
       [86, 82],
       [82, 90],
       [78, 80],
       [92, 94]])

In [120]:
b = np.array([[0.7], [0.3]])

In [121]:
b

array([[0.7],
       [0.3]])

In [122]:
np.dot(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [123]:
np.matmul(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [124]:
np.dot(a,10)

array([[800, 860],
       [820, 800],
       [850, 780],
       [900, 900],
       [860, 820],
       [820, 900],
       [780, 800],
       [920, 940]])

In [ ]:
# np.matmul(a,10)