In [1]:
import pandas as pd
import numpy as np

# series
## series的创建 pd.Series(date = None,index=None,dtype=None)

In [2]:
pd.Series(np.arange(9))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
dtype: int64

In [3]:
pd.Series([1.2,2.5,4.5,5.0],index=[1,2,3,4])

1    1.2
2    2.5
3    4.5
4    5.0
dtype: float64

In [4]:
color_count = pd.Series({"red":10,"green":20,"blue":100})

## series的属性

In [5]:
#ser.iloc[pos]

In [6]:
color_count.index

Index(['red', 'green', 'blue'], dtype='object')

In [7]:
color_count.values

array([ 10,  20, 100])

color_count[0]

In [8]:
color_count[1]


C:\Users\91168\AppData\Local\Temp\ipykernel_5756\586664262.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  color_count[1]


np.int64(20)

In [9]:
color_count.iloc[0]

np.int64(10)

# DataFrame
## DataFrame创建

In [10]:
pd.DataFrame(np.random.randn(2,3))

0         1         2
0 -1.504846  0.620910 -1.154003
1  1.900675  0.328838 -1.443917

In [11]:
score = np.random.randint(40,100,(10,5))

In [12]:
score

array([[62, 44, 89, 47, 82],
       [98, 61, 67, 79, 93],
       [50, 67, 85, 81, 77],
       [76, 45, 50, 43, 48],
       [64, 63, 64, 99, 67],
       [93, 41, 77, 98, 57],
       [64, 85, 55, 61, 53],
       [69, 70, 90, 64, 47],
       [65, 87, 46, 86, 56],
       [63, 73, 75, 49, 55]], dtype=int32)

In [13]:
score_df = pd.DataFrame(score)

In [14]:
subjects = ["语文", "数学", "英语", "政治", "体育"]

stu = ["同学"+ str(i) for i in range(score_df.shape[0])]

data = pd.DataFrame(score, columns=subjects, index=stu)

In [15]:
data

语文  数学  英语  政治  体育
同学0  62  44  89  47  82
同学1  98  61  67  79  93
同学2  50  67  85  81  77
同学3  76  45  50  43  48
同学4  64  63  64  99  67
同学5  93  41  77  98  57
同学6  64  85  55  61  53
同学7  69  70  90  64  47
同学8  65  87  46  86  56
同学9  63  73  75  49  55

In [16]:
score_df.shape[0]

10

## DataFrame的属性

In [17]:
data.shape

(10, 5)

In [18]:
data.index

Index(['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9'], dtype='object')

In [19]:
data.columns

Index(['语文', '数学', '英语', '政治', '体育'], dtype='object')

In [20]:
data.T

同学0  同学1  同学2  同学3  同学4  同学5  同学6  同学7  同学8  同学9
语文   62   98   50   76   64   93   64   69   65   63
数学   44   61   67   45   63   41   85   70   87   73
英语   89   67   85   50   64   77   55   90   46   75
政治   47   79   81   43   99   98   61   64   86   49
体育   82   93   77   48   67   57   53   47   56   55

In [21]:
data.values

array([[62, 44, 89, 47, 82],
       [98, 61, 67, 79, 93],
       [50, 67, 85, 81, 77],
       [76, 45, 50, 43, 48],
       [64, 63, 64, 99, 67],
       [93, 41, 77, 98, 57],
       [64, 85, 55, 61, 53],
       [69, 70, 90, 64, 47],
       [65, 87, 46, 86, 56],
       [63, 73, 75, 49, 55]], dtype=int32)

In [22]:
data.head()

语文  数学  英语  政治  体育
同学0  62  44  89  47  82
同学1  98  61  67  79  93
同学2  50  67  85  81  77
同学3  76  45  50  43  48
同学4  64  63  64  99  67

In [23]:
data.head(3)

语文  数学  英语  政治  体育
同学0  62  44  89  47  82
同学1  98  61  67  79  93
同学2  50  67  85  81  77

In [24]:
data.tail()

语文  数学  英语  政治  体育
同学5  93  41  77  98  57
同学6  64  85  55  61  53
同学7  69  70  90  64  47
同学8  65  87  46  86  56
同学9  63  73  75  49  55

## DataFrame索引值的设置

In [25]:
stu = ["同学_"+ str(i) for i in range(score_df.shape[0])]

In [26]:
stu

['同学_0',
 '同学_1',
 '同学_2',
 '同学_3',
 '同学_4',
 '同学_5',
 '同学_6',
 '同学_7',
 '同学_8',
 '同学_9']

In [27]:
data.index = stu

In [28]:
data

语文  数学  英语  政治  体育
同学_0  62  44  89  47  82
同学_1  98  61  67  79  93
同学_2  50  67  85  81  77
同学_3  76  45  50  43  48
同学_4  64  63  64  99  67
同学_5  93  41  77  98  57
同学_6  64  85  55  61  53
同学_7  69  70  90  64  47
同学_8  65  87  46  86  56
同学_9  63  73  75  49  55

In [29]:
# data.index[2] = "1"

In [30]:
# reset_index 重置缩影

In [31]:
data.reset_index()

index  语文  数学  英语  政治  体育
0  同学_0  62  44  89  47  82
1  同学_1  98  61  67  79  93
2  同学_2  50  67  85  81  77
3  同学_3  76  45  50  43  48
4  同学_4  64  63  64  99  67
5  同学_5  93  41  77  98  57
6  同学_6  64  85  55  61  53
7  同学_7  69  70  90  64  47
8  同学_8  65  87  46  86  56
9  同学_9  63  73  75  49  55

In [32]:
data.reset_index(drop=True)

语文  数学  英语  政治  体育
0  62  44  89  47  82
1  98  61  67  79  93
2  50  67  85  81  77
3  76  45  50  43  48
4  64  63  64  99  67
5  93  41  77  98  57
6  64  85  55  61  53
7  69  70  90  64  47
8  65  87  46  86  56
9  63  73  75  49  55

In [33]:
# set_index 设置缩影

In [49]:
df = pd.DataFrame({'month': [1, 4, 7, 10],
                    'year': [2012, 2014, 2013, 2014],
                    'sale':[55, 40, 84, 31]})

In [50]:
df

month  year  sale
0      1  2012    55
1      4  2014    40
2      7  2013    84
3     10  2014    31

In [51]:
df.set_index("year")

month  sale
year             
2012      1    55
2014      4    40
2013      7    84
2014     10    31

In [52]:
df = df.set_index(["year","month"])

# MultiIndex与Panel
## MultiIndex

df

In [54]:
df.index

MultiIndex([(2012,  1),
            (2014,  4),
            (2013,  7),
            (2014, 10)],
           names=['year', 'month'])

In [55]:
df.index.names

FrozenList(['year', 'month'])

In [56]:
df.index.levels

FrozenList([[2012, 2013, 2014], [1, 4, 7, 10]])

In [60]:
arrays = [["red","green","blue"],[1,1,2]]

In [61]:
pd.MultiIndex.from_arrays(arrays,names=("color","num"))

MultiIndex([(  'red', 1),
            ('green', 1),
            ( 'blue', 2)],
           names=['color', 'num'])

## panel

In [63]:
# p = pd.Panel(data=np.arange(24).reshape(4,3,2),
#                  items=list('ABCD'),
#                  major_axis=pd.date_range('20130101', periods=3),
#                  minor_axis=['first', 'second'])