In [1]:
import numpy as np
from hmmlearn import hmm

In [24]:
np.random

TypeError: 'module' object is not iterable

In [105]:
# 生成一些随机数据作为示例
# 假设观测数据为二维连续值
np.random.seed(0)
observations =np.concatenate([                  
    np.random.normal(loc=0.0, scale=0.5, size=(100, 2)),
    np.random.normal(loc=5.0, scale=0.5, size=(100, 2)),
    np.random.normal(loc=10.0, scale=0.5, size=(100, 2))
])
np.random.shuffle(observations)

In [107]:
# 创建高斯隐马尔可夫模型
model = hmm.GaussianHMM(n_components=3, covariance_type="full", n_iter=500)


In [109]:
# 训练模型
model.fit(observations)

G:\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(


GaussianHMM(covariance_type='full', n_components=3, n_iter=500)

In [110]:
# 预测隐状态序列
hidden_states = model.predict(observations)
hidden_states

array([1, 0, 0, 1, 1, 0, 2, 2, 0, 1, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1,
       1, 1, 2, 1, 2, 0, 2, 0, 0, 2, 1, 0, 2, 0, 0, 0, 0, 1, 1, 1, 2, 1,
       0, 2, 2, 2, 2, 1, 1, 1, 2, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 2, 2, 2,
       2, 1, 0, 1, 0, 2, 1, 1, 2, 2, 0, 0, 1, 2, 0, 1, 2, 0, 0, 1, 1, 0,
       2, 1, 0, 1, 0, 1, 0, 1, 0, 2, 1, 2, 1, 1, 2, 1, 1, 0, 0, 2, 0, 0,
       0, 0, 0, 2, 1, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 1, 2,
       2, 0, 1, 0, 1, 2, 0, 1, 2, 2, 2, 1, 2, 1, 0, 2, 2, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 2, 0, 1, 2, 2, 2, 0, 1, 1, 1, 2, 2, 1, 1, 1,
       1, 2, 2, 1, 2, 1, 1, 0, 2, 1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 2, 1, 2,
       1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 2, 1, 0, 0, 0, 1, 2, 1, 1, 2, 1,
       0, 0, 1, 0, 2, 2, 2, 1, 1, 0, 2, 2, 2, 0, 2, 1, 0, 0, 1, 0, 0, 2,
       1, 0, 2, 1, 1, 2, 1, 2, 2, 2, 0, 1, 2, 2, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 2, 2, 0, 1, 1, 0, 0, 0, 2, 0, 2, 0, 0, 2, 2, 2, 0, 2, 1, 2,
       0, 1, 2, 0, 0, 2, 0, 0, 0, 2, 1, 0, 2, 2], d

In [111]:
# 输出模型的参数
print("Transition matrix:")
print(model.transmat_)
print("\nMeans and variances of each hidden state:")
for i in range(model.n_components):
    print(f"Hidden state {i}")
    print("Mean = ", model.means_[i])
    print("Variance = ", np.diag(model.covars_[i]))

Transition matrix:
[[0.41       0.3        0.29      ]
 [0.31       0.33       0.36      ]
 [0.28282828 0.36363636 0.35353535]]

Means and variances of each hidden state:
Hidden state 0
Mean =  [4.92846083 4.94352468]
Variance =  [0.23226104 0.21269348]
Hidden state 1
Mean =  [-0.00047884  0.07138933]
Variance =  [0.26119949 0.25807023]
Hidden state 2
Mean =  [9.94382124 9.94843116]
Variance =  [0.27039246 0.26181956]


In [118]:
# 假设有3种隐状态(天气)：晴天(0), 多云(1), 雨天(2)
# 有3种观测值(活动)：散步(0), 购物(1), 在家看电影(2)

# 生成一些观察序列作为训练数据
# 观察序列表示一系列活动
observations = np.array([
    [0, 1, 2, 0, 1, 1, 0, 2, 2, 0],   # 第一个观测序列
    [1, 1, 2, 2, 0, 0, 1, 1, 2, 2],   # 第二个观测序列
    [0, 0, 1, 1, 2, 2, 1, 0, 2, 0]    # 第三个观测序列
]).T  # 转置，使其成为适合hmmlearn的输入格式 (每一列是一个时间步)

In [166]:
observations = np.array([
    [5, 2, 3],    # 第1个时间步的活动分布
    [4, 3, 3],    # 第2个时间步的活动分布
    [2, 6, 2],    # 第3个时间步的活动分布
    [0, 5, 5],    # 第4个时间步的活动分布
    [3, 3, 4],    # 第5个时间步的活动分布
    [1, 7, 2],    # 第6个时间步的活动分布
    [3, 4, 3],    # 第7个时间步的活动分布
    [5, 3, 2],    # 第8个时间步的活动分布
    [6, 2, 2],    # 第9个时间步的活动分布
    [4, 4, 2],    # 第10个时间步的活动分布
])

In [168]:
# 创建多项式隐马尔可夫模型
model = hmm.MultinomialHMM(n_components=3, n_iter=100, init_params="ste")

MultinomialHMM has undergone major changes. The previous version was implementing a CategoricalHMM (a special case of MultinomialHMM). This new implementation follows the standard definition for a Multinomial distribution (e.g. as in https://en.wikipedia.org/wiki/Multinomial_distribution). See these issues for details:
https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340


In [170]:
# 初始化模型参数（可选）
model.startprob_ = np.array([0.6, 0.3, 0.1])  # 初始状态概率
model.transmat_ = np.array([
    [0.7, 0.2, 0.1],
    [0.3, 0.5, 0.2],
    [0.3, 0.3, 0.4]
])  # 状态转移矩阵
model.emissionprob_ = np.array([
    [0.6, 0.3, 0.1],
    [0.3, 0.4, 0.3],
    [0.2, 0.2, 0.6]
])  # 观测概率矩阵 (每个状态对应的观测分布)


In [172]:
# 训练模型
model.fit(observations)

Even though the 'startprob_' attribute is set, it will be overwritten during initialization because 'init_params' contains 's'
Even though the 'transmat_' attribute is set, it will be overwritten during initialization because 'init_params' contains 't'


MultinomialHMM(n_components=3, n_iter=100,
               n_trials=array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10]),
               random_state=RandomState(MT19937) at 0x2DF1398D340)

In [174]:
# 测试：对新的观测序列预测最可能的天气状态序列
test_observations = np.array([[3, 3, 4],  # 第1个时间步的活动分布
    [2, 6, 2],  # 第2个时间步的活动分布
    [4, 3, 3], ])
predicted_states = model.predict(test_observations)


In [176]:
print("Predicted hidden states (weather):", predicted_states)

Predicted hidden states (weather): [1 2 0]


In [178]:
# 输出模型的参数
print("Transition matrix:")
print(model.transmat_)
print("\nEmission probability matrix:")
print(model.emissionprob_)

Transition matrix:
[[8.06844740e-01 1.92894377e-01 2.60883293e-04]
 [8.76924312e-04 2.12531641e-06 9.99120950e-01]
 [9.75089843e-01 1.41505836e-05 2.48960064e-02]]

Emission probability matrix:
[[0.22223825 0.47836381 0.29939794]
 [0.50383112 0.24300702 0.25316186]
 [0.47445033 0.27592852 0.24962115]]
