In [11]:
import numpy as np

# 定义状态和观察的名称索引
states = ['Sunny', 'Rainy']
observations = ['Walk', 'Shop', 'Clean']
state_to_index = {state: i for i, state in enumerate(states)}
obs_to_index = {obs: i for i, obs in enumerate(observations)}

# 初始概率分布
start_prob = np.array([0.6, 0.4])  # [P(Sunny), P(Rainy)]

# 状态转移概率矩阵
transition_prob = np.array([
    [0.8, 0.2],  # Sunny -> [Sunny, Rainy]
    [0.4, 0.6]   # Rainy -> [Sunny, Rainy]
])

# 发射概率矩阵（观测概率）
emission_prob = np.array([
    [0.6, 0.3, 0.1],  # Sunny -> [Walk, Shop, Clean]
    [0.1, 0.4, 0.5]   # Rainy -> [Walk, Shop, Clean]
])

# 观察序列
observed_sequence = ['Walk', 'Shop', 'Clean']


In [25]:
n_states = len(states)
n_observations = len(observed_sequence)

# 维特比矩阵 V，用来存储到每个时刻每个状态的最大概率
V = np.zeros((n_states, n_observations))
print(V)
# 路径矩阵，用来记录最大概率路径的前一个状态
path = np.zeros((n_states, n_observations), dtype=int)
print(path)
# 初始化第一列（时间 t=0）
for s in range(n_states):
    V[s, 0] = start_prob[s] * emission_prob[s, obs_to_index[observed_sequence[0]]]
    path[s, 0] = 0


[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]


In [15]:
# 动态规划填充维特比矩阵 V
for t in range(1, n_observations):
    for s in range(n_states):
        # 计算从前一个时刻的所有状态转移到当前状态 s 的最大概率
        probabilities = [
            V[prev_s, t-1] * transition_prob[prev_s, s] * emission_prob[s, obs_to_index[observed_sequence[t]]]
            for prev_s in range(n_states)
        ]
        V[s, t] = max(probabilities)
        path[s, t] = np.argmax(probabilities)


In [16]:
# 终止状态：找到最后一列的最大概率的状态
best_path_prob = max(V[:, -1])
best_last_state = np.argmax(V[:, -1])

# 反向追踪最优路径
best_path = [best_last_state]
for t in range(n_observations - 1, 0, -1):
    best_path.insert(0, path[best_path[0], t])

# 将状态索引转换为状态名称
best_path_states = [states[state] for state in best_path]
print("最优路径:", best_path_states)
print("最优路径概率:", best_path_prob)


最优路径: ['Sunny', 'Sunny', 'Rainy']
最优路径概率: 0.00864
